---
- hosts: test-server
  become: yes
  tasks:
  - name: install docker
    #apt:
    yum:
      pkg: docker.io
      state: present

  - name: start docker service
    service:
      name: docker
      state: started
      enabled: true

  - name: deploy addressbook application
    command: docker run -itd -p 8090:8080 sarojdevops/webappv2

